### ISSUE TITLE
JDK 11 support aka update glassfish jersey

### ISSUE THREAD

**Issue by jbaron** [WojciechZankowski/iextrading4j#121]
Right now it is not possible to use iextrading4j in JDK 11 or lower due to a bug in of the dependent libraries that was used (although not all features impacted by this).

The exception that will be thrown is:

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/glassfish/jersey/internal/jsr166/SubmissionPublisherFactory has been compiled by a more recent version of the Java Runtime (class file version 56.0), this version of the Java Runtime only recognizes class file versions up to 55.0
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.glassfish.jersey.internal.util.JerseyPublisher.<init>(JerseyPublisher.java:44)
	at org.glassfish.jersey.media.sse.internal.JerseySseEventSource.<init>(JerseySseEventSource.java:91)
	at org.glassfish.jersey.media.sse.internal.JerseySseEventSource.<init>(JerseySseEventSource.java:39)
	at org.glassfish.jersey.media.sse.internal.JerseySseEventSource$Builder.build(JerseySseEventSource.java:222)
	at org.glassfish.jersey.media.sse.internal.JerseySseEventSource$Builder.build(JerseySseEventSource.java:199)
	at pl.zankowski.iextrading4j.client.sse.manager.SseManager.subscribe(SseManager.java:29)
	at pl.zankowski.iextrading4j.client.sse.endpoint.GenericSseEndpoint.subscribe(GenericSseEndpoint.java:19)
	at pl.zankowski.iextrading4j.client.IEXTradingClient.subscribe(IEXTradingClient.java:101)
	at org.roboquant.feeds.iex.IEXLive.subscribeTrades(IEXLive.kt:83)
	at org.roboquant.MainKt.feedIEXLive(main.kt:77)
	at org.roboquant.MainKt.main(main.kt:105)
	at org.roboquant.MainKt.main(main.kt)
```

BTW, the mentioned class file version 56 is JDK 12

The is a bug in glassfish jersey. If you would update the dependency in the pom from 2.30 to 2.30.1 they fixed it.

 ```
  <dependency>
            <groupId>org.glassfish.jersey.core</groupId>
            <artifactId>jersey-common</artifactId>
            <version>2.30.1</version>
   </dependency>

```
I put the above also in my own pom file to force to load this instead of 2.30 and indeed the exception goes away.

P.S iextrading4j is very nice library, I use it in an algo-trading framework written in Kotlin called roboquant.

**Comment by jbaron** [comment]
Right now not supporting iex cloud anymore in roboquant due to changes in their direction. So this ticket can be closed.
