### ISSUE TITLE
Illegala argument exception thrown if the symbol has '$' symbol

### ISSUE THREAD

**Issue by adilkaraoz** [WojciechZankowski/iextrading4j#132]
**Describe the bug**
A new symbol is added as 'JNJ$', that's why now RestManager.java now throws IllegalArgumentException

**To Reproduce**
1. Request for key stats (as an example, the others also have the same problem) with the symbol 'JNJ$'
2. IllegalArgumentException will be thrown afterward from RestManager.java

**Expected behavior**
IllegalArgumentException won't be thrown and the response will be parsed successfully 

**Additional context**
Caused by: java.lang.IllegalArgumentException: Illegal group reference: group index is missing
	at java.base/java.util.regex.Matcher.appendExpandedReplacement(Unknown Source)
	at java.base/java.util.regex.Matcher.appendReplacement(Unknown Source)
	at java.base/java.util.regex.Matcher.replaceFirst(Unknown Source)
	at java.base/java.lang.String.replaceFirst(Unknown Source)
	at pl.zankowski.iextrading4j.client.rest.manager.RestManager.createPath(RestManager.java:94)
	at pl.zankowski.iextrading4j.client.rest.manager.RestManager.createURL(RestManager.java:73)
	at pl.zankowski.iextrading4j.client.rest.manager.RestManager.executeRequest(RestManager.java:30)
	at pl.zankowski.iextrading4j.client.rest.AbstractRestEndpoint.execute(AbstractRestEndpoint.java:16)
	at pl.zankowski.iextrading4j.client.rest.endpoint.GenericRestEndpoint.executeRequest(GenericRestEndpoint.java:14)

<img width="903" alt="image" src="https://github.com/WojciechZankowski/iextrading4j/assets/14542900/53d7147a-140d-4a9c-af39-2911465a90a6">

**Comment by adilkaraoz** [comment]
solution suggestion. You can send entry.getValue() to the following method and replace the path with the response.

`public static String replaceAll(String source, String key, String value){
    String[] split = source.split(Pattern.quote(key));
    StringBuilder builder = new StringBuilder();
    builder.append(split[0]);
    for (int i = 1; i < split.length; i++) {
        builder.append(value);
        builder.append(split[i]);
    }
    while (source.endsWith(key)) {
        builder.append(value);
        source = source.substring(0, source.length() - key.length());
    }
    return builder.toString();
}`
