### ISSUE TITLE
DeepSseRequestBuilder sse streaming data comes as Array - deserialization error

### ISSUE THREAD

**Issue by karlnicholas** [WojciechZankowski/iextrading4j#63]
**Describe the bug**
Attempting to stream DEEP data gives `Cannot deserialize` error .

**To Reproduce**

		final IEXCloudClient cloudClient = IEXTradingClient.create(IEXTradingApiVersion.IEX_CLOUD_BETA_SANDBOX,
				new IEXCloudTokenBuilder().withPublishableToken("Tpk_18dfe6cebb4f41ffb219b9680f9acaf2")
						.withSecretToken("Tsk_3eedff6f5c284e1a8b9bc16c54dd1af3").build());
        final String symbol = "IBM";
        final Consumer<DeepAsyncResponse<DeepResult>> deepConsumer = System.out::println;

        final SseRequest<DeepAsyncResponse<DeepResult>> request = new DeepSseRequestBuilder()
                .withSymbol(symbol)
                .build();
		
        cloudClient.subscribe(request, deepConsumer);

**Expected behavior**
Expected to see streaming data

**Screenshots**

	Jul 15, 2019 12:30:28 PM org.glassfish.jersey.media.sse.internal.JerseySseEventSource lambda$static$1
	WARNING: Subscriber.onError() called on subscriber with no registered error handler.
	javax.ws.rs.ProcessingException: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `pl.zankowski.iextrading4j.client.socket.request.marketdata.deep.DeepAsyncResponse` out of START_ARRAY token
	 at [Source: (ByteArrayInputStream); line: 1, column: 1]
		at org.glassfish.jersey.media.sse.InboundEvent.readAndCast(InboundEvent.java:373)
		at org.glassfish.jersey.media.sse.InboundEvent.readData(InboundEvent.java:359)
		at pl.zankowski.iextrading4j.client.sse.manager.SseManager.lambda$0(SseManager.java:38)
		at org.glassfish.jersey.media.sse.internal.JerseySseEventSource$1.onNext(JerseySseEventSource.java:146)
		at org.glassfish.jersey.media.sse.internal.JerseySseEventSource$1.onNext(JerseySseEventSource.java:128)
		at org.glassfish.jersey.internal.util.JerseyPublisher$SubscriberWrapper.onNext(JerseyPublisher.java:391)
		at org.glassfish.jersey.internal.jsr166.SubmissionPublisher$BufferedSubscription.consume(SubmissionPublisher.java:1500)
		at org.glassfish.jersey.internal.jsr166.SubmissionPublisher$ConsumerTask.run(SubmissionPublisher.java:953)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)
	Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `pl.zankowski.iextrading4j.client.socket.request.marketdata.deep.DeepAsyncResponse` out of START_ARRAY token
	 at [Source: (ByteArrayInputStream); line: 1, column: 1]
		at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
		at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1343)
		at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1139)
		at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1093)
		at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromArray(BeanDeserializerBase.java:1461)
		at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:185)
		at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:161)
		at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1574)
		at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:965)
		at org.glassfish.jersey.jackson.internal.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:838)
		at org.glassfish.jersey.media.sse.InboundEvent.readAndCast(InboundEvent.java:365)
		... 12 more

**Additional context**

**Comment by WojciechZankowski** [comment]
Hey,

I revisited all SSE endpoint and fixed them. So all Quotes/DEEP/Last Trades endpoints should work since version 3.2.4

```
<dependency>
	<groupId>pl.zankowski</groupId>
	<artifactId>iextrading4j-all</artifactId>
	<version>3.2.4</version>
</dependency>
```

And for the problem you descried in an other ticket it would be good to take a look at Book (DEEP) and Quote requests. They should have data for your needs.


Cheers,

Wojtek
