### ISSUE TITLE
Getting MessageBodyProviderNotFoundException

### ISSUE THREAD

**Issue by tchristofferson** [WojciechZankowski/iextrading4j#92]
```
[00:49:20] [Craft Scheduler Thread - 1/WARN]: java.util.concurrent.ExecutionException: org.glassfish.jersey.message.internal.MessageBodyProviderNotFoundException: MessageBodyReader not found for media type=application/json;charset=utf-8, type=class pl.zankowski.iextrading4j.api.stocks.Quote, genericType=class pl.zankowski.iextrading4j.api.stocks.Quote.
[00:49:20] [Craft Scheduler Thread - 1/WARN]: 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
[00:49:20] [Craft Scheduler Thread - 1/WARN]: 	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
[00:49:20] [Craft Scheduler Thread - 1/WARN]: 	at com.tchristofferson.stocks.commands.StocksCommand.lambda$check$6(StocksCommand.java:208)
[00:49:20] [Craft Scheduler Thread - 1/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81)
[00:49:20] [Craft Scheduler Thread - 1/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[00:49:20] [Craft Scheduler Thread - 1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[00:49:20] [Craft Scheduler Thread - 1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[00:49:20] [Craft Scheduler Thread - 1/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[00:49:20] [Craft Scheduler Thread - 1/WARN]: Caused by: org.glassfish.jersey.message.internal.MessageBodyProviderNotFoundException: MessageBodyReader not found for media type=application/json;charset=utf-8, type=class pl.zankowski.iextrading4j.api.stocks.Quote, genericType=class pl.zankowski.iextrading4j.api.stocks.Quote.
[00:49:20] [Craft Scheduler Thread - 1/WARN]: 	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:208)
[00:49:20] [Craft Scheduler Thread - 1/WARN]: 	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:132)
[00:49:20] [Craft Scheduler Thread - 1/WARN]: 	at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1067)
[00:49:20] [Craft Scheduler Thread - 1/WARN]: 	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:850)
[00:49:20] [Craft Scheduler Thread - 1/WARN]: 	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:810)
[00:49:20] [Craft Scheduler Thread - 1/WARN]: 	at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:339)
[00:49:20] [Craft Scheduler Thread - 1/WARN]: 	at org.glassfish.jersey.client.InboundJaxrsResponse$2.call(InboundJaxrsResponse.java:102)
[00:49:20] [Craft Scheduler Thread - 1/WARN]: 	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
[00:49:20] [Craft Scheduler Thread - 1/WARN]: 	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
[00:49:20] [Craft Scheduler Thread - 1/WARN]: 	at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
[00:49:20] [Craft Scheduler Thread - 1/WARN]: 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:365)
[00:49:20] [Craft Scheduler Thread - 1/WARN]: 	at org.glassfish.jersey.client.InboundJaxrsResponse.runInScopeIfPossible(InboundJaxrsResponse.java:240)
[00:49:20] [Craft Scheduler Thread - 1/WARN]: 	at org.glassfish.jersey.client.InboundJaxrsResponse.readEntity(InboundJaxrsResponse.java:99)
[00:49:20] [Craft Scheduler Thread - 1/WARN]: 	at pl.zankowski.iextrading4j.client.rest.manager.RestManager.executeRequest(RestManager.java:59)
[00:49:20] [Craft Scheduler Thread - 1/WARN]: 	at pl.zankowski.iextrading4j.client.rest.AbstractRestEndpoint.execute(AbstractRestEndpoint.java:16)
[00:49:20] [Craft Scheduler Thread - 1/WARN]: 	at pl.zankowski.iextrading4j.client.rest.endpoint.GenericRestEndpoint.executeRequest(GenericRestEndpoint.java:14)
[00:49:20] [Craft Scheduler Thread - 1/WARN]: 	at pl.zankowski.iextrading4j.client.IEXTradingClient.executeRequest(IEXTradingClient.java:90)
[00:49:20] [Craft Scheduler Thread - 1/WARN]: 	at com.tchristofferson.stocks.Stocks.lambda$getStockData$1(Stocks.java:164)
[00:49:20] [Craft Scheduler Thread - 1/WARN]: 	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
[00:49:20] [Craft Scheduler Thread - 1/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java)
[00:49:20] [Craft Scheduler Thread - 1/WARN]: 	... 3 more
```

```
RestRequest<Quote> request = new QuoteRequestBuilder()
                .withSymbol("aapl")
                .build();
return executorService.submit(() -> {
            try {
                Quote quote = cloudClient.executeRequest(request);//Error happens here
                return new StockData(quote, null);
            } catch (IEXTradingException e) {
                return new StockData(null, e.getMessage());
            }
});
```

dependencies:
```
<dependencies>
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <version>1.8.8-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.tchristofferson</groupId>
            <artifactId>API</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>com.tchristofferson</groupId>
            <artifactId>PersistentStorageAPI</artifactId>
            <version>1.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>co.aikar</groupId>
            <artifactId>acf-bukkit</artifactId>
            <version>0.5.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>pl.zankowski</groupId>
            <artifactId>iextrading4j-all</artifactId>
            <version>3.3.2</version>
        </dependency>
        <dependency>
            <groupId>com.github.MilkBowl</groupId>
            <artifactId>VaultAPI</artifactId>
            <version>1.7</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
```

**Comment by tchristofferson** [comment]
Adding this to my pom fixes the issue:
```
<dependency>
    <groupId>com.owlike</groupId>
    <artifactId>genson</artifactId>
    <version>1.3</version>
</dependency>
```
I am not sure why. Any insight on why this is would be helpful.
